
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoylwkrhbyoknjcmxigu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhveWx3a3JoYnlva25qY214aWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMzk2MjIsImV4cCI6MjA1MjcxNTYyMn0._KmxtHUi7N7xaAFM9kAhTu-4-OiRd95tZfG-zZfL5m4";

// Force explicit options for session persistence and refresh
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
